### ISSUE TITLE
This has to be compiled for every platform

### ISSUE THREAD

**Issue by agauniyal** [ikalnitsky/termcolor#2]
Right?

**Comment by ikalnitsky** [comment]
@agauniyal I'm not exactly understand what do you mean. The library itself is header-only, so once you include it it will be compiled within your project.

**Comment by agauniyal** [comment]
ah, I skipped over the readme. Ignore my stupidity :smile:

**Comment by ikalnitsky** [comment]
@agauniyal no problem ;)
